version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: sa_sysprospect
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sysprospect
    ports:
      - "5432:5432"
    networks:
      - sysprospect

  localstack:
    build:
      context: ./localstack
    environment:
      - SERVICES=sns,sqs    
      - CORS_ALLOW_ORIGIN=*            
    ports:
      - "4566:4566"     
    networks:
      - sysprospect        

  webservice:
    build:
      context: ./webservice
    ports:
      - "8080:8080"
    networks:
      - sysprospect

  webapp:
    build:
      context: ./webapp
    ports:
      - "8090:80"
    networks:
      - sysprospect            

networks:
  sysprospect:
    driver: bridge